/**
 * Legal document content, in English and Bahasa Malaysia.
 *
 * Section 7(2) of the Personal Data Protection Act 2010 requires the personal
 * data protection notice to be issued in both the national language and
 * English, so every document here carries both and the page offers a toggle
 * rather than separate routes — one URL to share, no risk of one language
 * quietly falling out of date behind the other.
 *
 * These documents describe the site as it actually behaves. The claims about
 * cookies and tracking were verified against the live site: no Set-Cookie
 * header is returned on any route, no analytics or pixel is loaded, and fonts
 * are self-hosted rather than fetched from a third-party CDN. If any of that
 * changes, this file changes in the same commit.
 */

export type Locale = "en" | "ms"

export type LegalSection = {
  heading: string
  /** Paragraphs, rendered in order. */
  body?: string[]
  /** Rendered as a bulleted list after the paragraphs. */
  list?: string[]
}

export type LegalDoc = {
  slug: "privacy" | "cookies" | "terms"
  title: string
  /** One-line description used on the /legal index and as the page lede. */
  summary: string
  intro: string[]
  sections: LegalSection[]
}

/** Shown as "Last updated" on every document. */
export const LEGAL_UPDATED = "28 July 2026"

/** Published contact point for data access and correction requests. */
export const LEGAL_CONTACT = "president@emergingleadersasia.com"

export const UI_STRINGS: Record<Locale, Record<string, string>> = {
  en: {
    legalIndexTitle: "Legal",
    legalIndexLede:
      "How we handle your information, what we store on your device, and the terms you agree to by using this site.",
    lastUpdated: "Last updated",
    switchLanguage: "Bahasa Malaysia",
    backToLegal: "All legal documents",
    reviewNotice:
      "This notice is provided in English and Bahasa Malaysia. Both versions describe the same practices.",
  },
  ms: {
    legalIndexTitle: "Perundangan",
    legalIndexLede:
      "Bagaimana kami mengendalikan maklumat anda, apa yang kami simpan pada peranti anda, dan terma yang anda persetujui dengan menggunakan laman ini.",
    lastUpdated: "Kemas kini terakhir",
    switchLanguage: "English",
    backToLegal: "Semua dokumen perundangan",
    reviewNotice:
      "Notis ini disediakan dalam Bahasa Inggeris dan Bahasa Malaysia. Kedua-dua versi menerangkan amalan yang sama.",
  },
}

const PRIVACY_EN: LegalDoc = {
  slug: "privacy",
  title: "Personal Data Protection Notice",
  summary: "What personal data we collect, why we collect it, and your rights under the PDPA.",
  intro: [
    "Emerging Leaders Asia (“ELA”, “we”, “us”) is committed to protecting the personal data you share with us. This notice is issued under the Personal Data Protection Act 2010 (“PDPA”) and explains what we collect, why, and what you can ask us to do about it.",
    "It applies to emergingleadersasia.com. It does not apply to other websites we link to, which have their own policies.",
  ],
  sections: [
    {
      heading: "Data we collect automatically",
      body: [
        "None. This website does not set cookies, run analytics, embed tracking pixels, or load scripts or fonts from third-party servers. Browsing this site stores nothing on your device and creates no profile of you.",
        "Our web host, Hostinger, keeps standard server logs that may include your IP address, as any web server does. These are generated by the hosting infrastructure for security and reliability, not by us for analysis, and we do not use them to identify individual visitors.",
      ],
    },
    {
      heading: "Data you give us directly",
      body: [
        "If you submit the intake form on our Join page, we collect the information you enter so that we can respond to you:",
      ],
      list: [
        "Your name",
        "Your email address",
        "What you are approaching us about — alumni membership, committee, partnership, or something else",
        "Your AYTP track, if you have one",
        "Anything you write in the free-text message field",
      ],
    },
    {
      heading: "Why we use it",
      body: [
        "We use what you submit only to reply to you, to assess membership, committee or partnership enquiries, and to keep in touch about the opportunity you approached us about.",
        "We do not sell your personal data. We do not share it with advertisers. We do not use it for automated decision-making or profiling.",
      ],
    },
    {
      heading: "Who else sees it",
      body: [
        "Your submission is handled by the ELA committee members responsible for intake. We use Hostinger for website hosting and email, which means your data is stored on their servers as our service provider.",
        "We will disclose personal data to third parties only where you have consented, or where we are required to by law.",
      ],
    },
    {
      heading: "How long we keep it",
      body: [
        "We keep intake submissions for as long as needed to deal with your enquiry and any resulting relationship with the network. If you ask us to delete your data and we have no legal reason to keep it, we will.",
      ],
    },
    {
      heading: "Your rights",
      body: ["Under the PDPA you may, at any time:"],
      list: [
        "Ask for a copy of the personal data we hold about you",
        "Ask us to correct data that is inaccurate, incomplete or out of date",
        "Withdraw your consent to us processing your data",
        "Ask us to limit how we process your data",
        "Ask us to delete your data, where we have no legal reason to retain it",
        "Lodge a complaint with the Personal Data Protection Commissioner of Malaysia",
      ],
    },
    {
      heading: "Contact us",
      body: [
        `To exercise any of these rights, or to ask anything about this notice, write to ${LEGAL_CONTACT}. We aim to respond within 21 days.`,
      ],
    },
    {
      heading: "Changes to this notice",
      body: [
        "If we change how we handle personal data — for example by introducing website analytics — we will update this notice and change the date at the top of this page before the change takes effect.",
      ],
    },
  ],
}

const PRIVACY_MS: LegalDoc = {
  slug: "privacy",
  title: "Notis Perlindungan Data Peribadi",
  summary:
    "Data peribadi yang kami kumpul, sebab kami mengumpulnya, dan hak anda di bawah APDP.",
  intro: [
    "Emerging Leaders Asia (“ELA”, “kami”) komited untuk melindungi data peribadi yang anda kongsi dengan kami. Notis ini dikeluarkan di bawah Akta Perlindungan Data Peribadi 2010 (“APDP”) dan menerangkan apa yang kami kumpul, sebabnya, dan apa yang boleh anda minta kami lakukan mengenainya.",
    "Notis ini terpakai bagi emergingleadersasia.com. Ia tidak terpakai bagi laman web lain yang kami pautkan, yang mempunyai dasar masing-masing.",
  ],
  sections: [
    {
      heading: "Data yang kami kumpul secara automatik",
      body: [
        "Tiada. Laman web ini tidak menetapkan kuki, tidak menjalankan analitik, tidak membenamkan piksel penjejakan, dan tidak memuatkan skrip atau fon daripada pelayan pihak ketiga. Melayari laman ini tidak menyimpan apa-apa pada peranti anda dan tidak mewujudkan sebarang profil tentang anda.",
        "Hos web kami, Hostinger, menyimpan log pelayan biasa yang mungkin mengandungi alamat IP anda, sebagaimana mana-mana pelayan web. Log ini dijana oleh infrastruktur hos untuk tujuan keselamatan dan kebolehpercayaan, bukan oleh kami untuk analisis, dan kami tidak menggunakannya untuk mengenal pasti pelawat secara individu.",
      ],
    },
    {
      heading: "Data yang anda berikan kepada kami",
      body: [
        "Jika anda menghantar borang permohonan di halaman Join kami, kami mengumpul maklumat yang anda masukkan supaya kami boleh membalas anda:",
      ],
      list: [
        "Nama anda",
        "Alamat e-mel anda",
        "Tujuan anda menghubungi kami — keahlian alumni, jawatankuasa, perkongsian, atau lain-lain",
        "Trek AYTP anda, jika ada",
        "Apa-apa yang anda tulis dalam ruangan mesej",
      ],
    },
    {
      heading: "Sebab kami menggunakannya",
      body: [
        "Kami menggunakan maklumat yang anda hantar semata-mata untuk membalas anda, menilai pertanyaan keahlian, jawatankuasa atau perkongsian, dan untuk terus berhubung mengenai peluang yang anda tanyakan.",
        "Kami tidak menjual data peribadi anda. Kami tidak berkongsinya dengan pengiklan. Kami tidak menggunakannya untuk membuat keputusan automatik atau pemprofilan.",
      ],
    },
    {
      heading: "Siapa lagi yang melihatnya",
      body: [
        "Penghantaran anda dikendalikan oleh ahli jawatankuasa ELA yang bertanggungjawab ke atas permohonan masuk. Kami menggunakan Hostinger untuk pengehosan laman web dan e-mel, yang bermakna data anda disimpan pada pelayan mereka sebagai penyedia perkhidmatan kami.",
        "Kami hanya akan mendedahkan data peribadi kepada pihak ketiga jika anda telah memberikan persetujuan, atau jika kami dikehendaki berbuat demikian oleh undang-undang.",
      ],
    },
    {
      heading: "Berapa lama kami menyimpannya",
      body: [
        "Kami menyimpan penghantaran borang selagi ia diperlukan untuk menguruskan pertanyaan anda dan sebarang hubungan yang terhasil dengan rangkaian ini. Jika anda meminta kami memadamkan data anda dan kami tiada sebab di sisi undang-undang untuk menyimpannya, kami akan memadamkannya.",
      ],
    },
    {
      heading: "Hak anda",
      body: ["Di bawah APDP, anda boleh pada bila-bila masa:"],
      list: [
        "Meminta salinan data peribadi yang kami simpan tentang anda",
        "Meminta kami membetulkan data yang tidak tepat, tidak lengkap atau sudah lapuk",
        "Menarik balik persetujuan anda terhadap pemprosesan data anda",
        "Meminta kami mengehadkan cara kami memproses data anda",
        "Meminta kami memadamkan data anda, jika kami tiada sebab di sisi undang-undang untuk menyimpannya",
        "Membuat aduan kepada Pesuruhjaya Perlindungan Data Peribadi Malaysia",
      ],
    },
    {
      heading: "Hubungi kami",
      body: [
        `Untuk melaksanakan mana-mana hak ini, atau untuk bertanya apa-apa mengenai notis ini, e-mel kami di ${LEGAL_CONTACT}. Kami berusaha untuk membalas dalam tempoh 21 hari.`,
      ],
    },
    {
      heading: "Perubahan kepada notis ini",
      body: [
        "Jika kami mengubah cara kami mengendalikan data peribadi — sebagai contoh dengan memperkenalkan analitik laman web — kami akan mengemas kini notis ini dan menukar tarikh di bahagian atas halaman ini sebelum perubahan itu berkuat kuasa.",
      ],
    },
  ],
}

const COOKIES_EN: LegalDoc = {
  slug: "cookies",
  title: "Cookies",
  summary: "We don't use any. Here's what that means, and what happens when you leave this site.",
  intro: [
    "Cookies are small files a website saves on your phone, tablet or computer when you visit.",
    "This website does not use them.",
  ],
  sections: [
    {
      heading: "What we don't do",
      body: [
        "We do not set cookies. We do not run analytics. We do not embed tracking pixels or advertising tags. We do not use local storage, or any other means of keeping information about you on your device.",
        "Because we store nothing about you on your device, there is nothing to consent to — which is why you have not been shown a cookie banner.",
      ],
    },
    {
      heading: "Fonts and images load from our own servers",
      body: [
        "Many websites pull fonts from a third-party service, which quietly shares your IP address with that provider on every page you open. Ours are served from our own domain, so your visit is not shared with any font provider.",
      ],
    },
    {
      heading: "When you leave this site",
      body: [
        "Some links take you to services we do not control — Instagram, Luma, and the Axiata application portal among them. Once you arrive there, those services set their own cookies under their own policies. This page covers emergingleadersasia.com only.",
      ],
    },
    {
      heading: "If this changes",
      body: [
        "We may add privacy-respecting analytics in future so we can see which pages are useful. If we do, we will update this page first, and we will not store anything on your device without asking you.",
      ],
    },
  ],
}

const COOKIES_MS: LegalDoc = {
  slug: "cookies",
  title: "Kuki",
  summary:
    "Kami tidak menggunakannya. Ini maksudnya, dan apa yang berlaku apabila anda meninggalkan laman ini.",
  intro: [
    "Kuki ialah fail kecil yang disimpan oleh sesebuah laman web pada telefon, tablet atau komputer anda semasa anda melawat.",
    "Laman web ini tidak menggunakannya.",
  ],
  sections: [
    {
      heading: "Apa yang kami tidak lakukan",
      body: [
        "Kami tidak menetapkan kuki. Kami tidak menjalankan analitik. Kami tidak membenamkan piksel penjejakan atau tag pengiklanan. Kami tidak menggunakan storan setempat, atau apa-apa cara lain untuk menyimpan maklumat tentang anda pada peranti anda.",
        "Oleh sebab kami tidak menyimpan apa-apa tentang anda pada peranti anda, tiada apa-apa yang memerlukan persetujuan — sebab itulah anda tidak ditunjukkan sepanduk kuki.",
      ],
    },
    {
      heading: "Fon dan imej dimuatkan dari pelayan kami sendiri",
      body: [
        "Banyak laman web memuatkan fon daripada perkhidmatan pihak ketiga, yang secara senyap berkongsi alamat IP anda dengan penyedia tersebut pada setiap halaman yang anda buka. Fon kami disajikan dari domain kami sendiri, jadi lawatan anda tidak dikongsi dengan mana-mana penyedia fon.",
      ],
    },
    {
      heading: "Apabila anda meninggalkan laman ini",
      body: [
        "Sesetengah pautan membawa anda ke perkhidmatan yang tidak kami kawal — antaranya Instagram, Luma, dan portal permohonan Axiata. Setibanya anda di sana, perkhidmatan tersebut menetapkan kuki mereka sendiri di bawah dasar mereka sendiri. Halaman ini hanya meliputi emergingleadersasia.com.",
      ],
    },
    {
      heading: "Jika ini berubah",
      body: [
        "Kami mungkin menambah analitik yang menghormati privasi pada masa hadapan supaya kami dapat melihat halaman mana yang berguna. Jika kami berbuat demikian, kami akan mengemas kini halaman ini terlebih dahulu, dan kami tidak akan menyimpan apa-apa pada peranti anda tanpa bertanya kepada anda.",
      ],
    },
  ],
}

const TERMS_EN: LegalDoc = {
  slug: "terms",
  title: "Terms of Use",
  summary: "The terms you agree to by using this website.",
  intro: [
    "By using emergingleadersasia.com you agree to these terms. If you do not agree with them, please do not use the site.",
  ],
  sections: [
    {
      heading: "About us",
      body: [
        "Emerging Leaders Asia is an alumni-led community and the alumni continuity engine of the Axiata Young Talent Programme. This website is operated by the ELA committee.",
      ],
    },
    {
      heading: "Using this site",
      body: ["You agree not to:"],
      list: [
        "Use the site for any unlawful purpose",
        "Attempt to gain unauthorised access to the site or the systems behind it",
        "Interfere with the site's operation or availability",
        "Copy or republish substantial parts of the site without our permission",
      ],
    },
    {
      heading: "Our content",
      body: [
        "The text, photographs, logos and design on this site belong to Emerging Leaders Asia or to the partners who licensed them to us, unless stated otherwise. The Axiata, Codex, Inspire Group and Axiata Foundation marks belong to their respective owners and appear here with permission.",
        "You may link to our pages and quote short extracts with attribution. Anything more needs our written permission.",
      ],
    },
    {
      heading: "Programme information",
      body: [
        "We work to keep programme details — dates, venues, eligibility, prizes and deadlines — accurate and current. They can change, and publication here is not an offer or a guarantee of a place. Selection into any ELA programme is at our discretion and subject to the criteria published for that programme.",
      ],
    },
    {
      heading: "Applications through third parties",
      body: [
        "Some programmes take applications through external platforms. When you follow a link to one of those, you are dealing with that provider under their terms and their privacy policy, not ours.",
      ],
    },
    {
      heading: "Links to other sites",
      body: [
        "We link to sites we do not control. We are not responsible for their content, their accuracy or how they handle your data.",
      ],
    },
    {
      heading: "Availability",
      body: [
        "We provide this site on an “as is” basis. We do not promise it will always be available or free of errors, and we are not liable for any loss arising from your use of it, to the extent the law allows.",
      ],
    },
    {
      heading: "Governing law",
      body: [
        "These terms are governed by the laws of Malaysia, and the courts of Malaysia have exclusive jurisdiction over any dispute arising from them.",
      ],
    },
    {
      heading: "Contact",
      body: [`Questions about these terms can go to ${LEGAL_CONTACT}.`],
    },
  ],
}

const TERMS_MS: LegalDoc = {
  slug: "terms",
  title: "Terma Penggunaan",
  summary: "Terma yang anda persetujui dengan menggunakan laman web ini.",
  intro: [
    "Dengan menggunakan emergingleadersasia.com, anda bersetuju dengan terma ini. Jika anda tidak bersetuju, sila jangan gunakan laman ini.",
  ],
  sections: [
    {
      heading: "Tentang kami",
      body: [
        "Emerging Leaders Asia ialah komuniti yang diterajui alumni dan merupakan enjin kesinambungan alumni bagi Axiata Young Talent Programme. Laman web ini dikendalikan oleh jawatankuasa ELA.",
      ],
    },
    {
      heading: "Menggunakan laman ini",
      body: ["Anda bersetuju untuk tidak:"],
      list: [
        "Menggunakan laman ini bagi apa-apa tujuan yang menyalahi undang-undang",
        "Cuba mendapatkan akses tanpa kebenaran kepada laman ini atau sistem di sebaliknya",
        "Mengganggu operasi atau ketersediaan laman ini",
        "Menyalin atau menerbitkan semula bahagian penting laman ini tanpa kebenaran kami",
      ],
    },
    {
      heading: "Kandungan kami",
      body: [
        "Teks, gambar, logo dan reka bentuk di laman ini adalah milik Emerging Leaders Asia atau rakan kongsi yang melesenkannya kepada kami, melainkan dinyatakan sebaliknya. Tanda Axiata, Codex, Inspire Group dan Axiata Foundation adalah milik pemilik masing-masing dan dipaparkan di sini dengan kebenaran.",
        "Anda boleh memaut ke halaman kami dan memetik petikan pendek dengan pengiktirafan. Selain itu, kebenaran bertulis kami diperlukan.",
      ],
    },
    {
      heading: "Maklumat program",
      body: [
        "Kami berusaha memastikan butiran program — tarikh, tempat, kelayakan, hadiah dan tarikh tutup — tepat dan terkini. Butiran ini boleh berubah, dan penerbitannya di sini bukan suatu tawaran atau jaminan tempat. Pemilihan ke mana-mana program ELA adalah atas budi bicara kami dan tertakluk kepada kriteria yang diterbitkan bagi program tersebut.",
      ],
    },
    {
      heading: "Permohonan melalui pihak ketiga",
      body: [
        "Sesetengah program menerima permohonan melalui platform luar. Apabila anda mengikuti pautan ke platform tersebut, anda berurusan dengan penyedia itu di bawah terma dan dasar privasi mereka, bukan kami.",
      ],
    },
    {
      heading: "Pautan ke laman lain",
      body: [
        "Kami memaut ke laman yang tidak kami kawal. Kami tidak bertanggungjawab ke atas kandungan, ketepatan, atau cara mereka mengendalikan data anda.",
      ],
    },
    {
      heading: "Ketersediaan",
      body: [
        "Kami menyediakan laman ini “sebagaimana adanya”. Kami tidak menjanjikan ia sentiasa tersedia atau bebas ralat, dan kami tidak bertanggungan ke atas sebarang kerugian akibat penggunaan anda, setakat yang dibenarkan undang-undang.",
      ],
    },
    {
      heading: "Undang-undang yang mentadbir",
      body: [
        "Terma ini ditadbir oleh undang-undang Malaysia, dan mahkamah Malaysia mempunyai bidang kuasa eksklusif ke atas sebarang pertikaian yang timbul daripadanya.",
      ],
    },
    {
      heading: "Hubungi",
      body: [`Sebarang pertanyaan mengenai terma ini boleh dihantar ke ${LEGAL_CONTACT}.`],
    },
  ],
}

export const LEGAL_DOCS: Record<Locale, LegalDoc[]> = {
  en: [PRIVACY_EN, COOKIES_EN, TERMS_EN],
  ms: [PRIVACY_MS, COOKIES_MS, TERMS_MS],
}

export function getLegalDoc(slug: LegalDoc["slug"], locale: Locale): LegalDoc {
  const doc = LEGAL_DOCS[locale].find((d) => d.slug === slug)
  if (!doc) throw new Error(`Unknown legal document: ${slug}`)
  return doc
}
